name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  tests:
  
    runs-on: macos-latest
    steps:
    – uses: actions/checkout@v2
    
    – name: Build for macOS
      run: swift build -v
    – name: Run macOS tests
      run: swift test -v
    – name: Run iOS tests
      run: sh ./Scripts/ci-ios-code-coverage.sh
